services:
  spark-master:
    build: .
    container_name: spark-master
    entrypoint: ["./entrypoint.sh", "master"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 10
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
      - "8888:8888"
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
      - ./warehouse:/
    networks:
      - spark-net
  spark-history-server:
    container_name: spark-history
    build: .
    entrypoint: ["./entrypoint.sh", "history"]
    depends_on:
      - spark-master
    env_file:
      - .env
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
      - ./warehouse:/
    ports:
      - "18080:18080"
    networks:
      - spark-net
  spark-worker:
    build: .
    entrypoint: ["./entrypoint.sh", "worker"]
    depends_on:
      - spark-master
    networks:
      - spark-net
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
      - ./warehouse:/opt/spark/warehouse
    env_file:
      - .env

networks:
  spark-net:
